# This rule is not used by the project pbs-job-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to batch.example.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pbs-job-operator
    app.kubernetes.io/managed-by: kustomize
  name: pbsjob-viewer-role
rules:
- apiGroups:
  - batch.example.com
  resources:
  - pbsjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.example.com
  resources:
  - pbsjobs/status
  verbs:
  - get
