#!/bin/bash

capsh --print | grep -Eq '*cap_sys_admin*'
if [ $? -eq 0 -a $(id -u) -eq 0 -a $(id -g) -eq 0 -a $# -eq 0 ]; then
	if [ -x "/usr/lib/systemd/systemd" ]; then
		exec /usr/lib/systemd/systemd --system
	elif [ -x "/lib/systemd/systemd" ]; then
		exec /lib/systemd/systemd --system
	elif [ -x "/usr/sbin/init" ]; then
		exec /usr/sbin/init
	elif [ -x "/sbin/init" ]; then
		exec /sbin/init
	else
		echo "Couldn't start container in systemd mode, starting in default mode"
	fi
fi
if [ $# -ne 0 ]; then
	exec "$@"
else
	exec /bin/bash
fi
