#!/usr/bin/sh

if [ $# -lt 3 ]
then
	echo "Usage is: $0 <start> <end> <port no.> [mom-name]"
	exit 
fi
. /etc/pbs.conf

l=$2
n=$1
port=$3
mom_name=""
if [ $# -eq 4 ]; then
	mom_name=$4
fi

port=$3
start_time=`date +%s`
while [ $n -le $l ]
do
	#echo "Adding node mom$n"
	if [ ! -z "$mom_name" ]; then
		$PBS_EXEC/bin/qmgr -c "c n mom$n mom=$mom_name, port=$port"
	else
		$PBS_EXEC/bin/qmgr -c "c n mom$n mom=mom$n, port=$port"
	fi
	port=`expr $port + 5`
	n=`expr $n + 1`
done

echo Done
