#!/usr/bin/sh
if [ $# -lt 2 ]
then
	echo "Usage: $0 <first> <last>"
	exit 1
fi

n=$2
l=$1

. /etc/pbs.conf
pbs_home=$PBS_HOME

pbs_newhome=`dirname $pbs_home`
if [ -z "$pbs_newhome" ]; then 
	echo "Could not detect new home"
	exit 1
fi

if [ ! -d "$pbs_newhome" ]; then 
	echo "$pbs_newhome is not a directory"
	exit 1
fi

if [ "$pbs_newhome" = "/" ]; then
	echo "pbs_newhome resolves to /. Cannot work"
	exit 1
fi

while [ $l -le $n ]
do
	${PBS_EXEC}/bin/qmgr -c "d n mom$l"
	l=`expr $l + 1`
done

rm out*
rm STD*
