#!/usr/bin/sh

. /etc/pbs.conf
pbs_home=$PBS_HOME
pbs_newhome=`dirname $pbs_home`
if [ -z "$pbs_newhome" ]; then 
	echo "Could not detect new home"
	exit 1
fi

if [ ! -d "$pbs_newhome" ]; then 
	echo "$pbs_newhome is not a directory"
	exit 1
fi

if [ "$pbs_newhome" = "/" ]; then
	echo "pbs_newhome resolves to /. Cannot work"
	exit 1
fi



while :
do
	out=`${PBS_EXEC}/bin/qselect`
	if [ ! -z "$out" ]; then
		${PBS_EXEC}/bin/qdel -Wforce `${PBS_EXEC}/bin/qselect`
		sleep 1
	else
		break
	fi
done

for node in `${PBS_EXEC}/bin/pbsnodes -av | grep "resources_available.vnode" | awk -F "=" '{print $2}' | tr -d " "`
do
	${PBS_EXEC}/bin/qmgr -c "d n $node"
done

