#!/usr/bin/sh -x


usage()
{
	echo "Usage is: $0 <start/stop> [port no.] [server-name]"
}

getpid() {
	if [ -f $1 ]; then
		cat $1
	else
		echo -1
	fi
}

common()
{

	. /etc/pbs.conf
	ulimit -n 10000
	ulimit -c unlimited

	pbs_home=$PBS_HOME
	pbs_newhome=`dirname $pbs_home`
	if [ -z "$pbs_newhome" ]; then 
		echo "Could not detect new home"
		exit 1
	fi

	if [ ! -d "$pbs_newhome" ]; then 
		echo "$pbs_newhome is not a directory"
		exit 1
	fi

	if [ "$pbs_newhome" = "/" ]; then
		echo "pbs_newhome resolves to /. Cannot work"
		exit 1
	fi

	echo Current PBS_HOME=$pbs_home
	echo Homes for new moms=$pbs_newhome

	n="_xl"

	return 0
}

start_mom()
{
	port=$1
	server=$2

	common

	echo "creating mom directory"
	mkdir $pbs_newhome/mom$n
	cp -r -p $pbs_home/aux $pbs_newhome/mom$n
	cp -r -p $pbs_home/checkpoint $pbs_newhome/mom$n
	cp -r -p $pbs_home/mom_logs $pbs_newhome/mom$n
	cp -r -p $pbs_home/pbs_environment $pbs_newhome/mom$n
	cp -r -p $pbs_home/mom_priv $pbs_newhome/mom$n
	cp -r -p $pbs_home/spool $pbs_newhome/mom$n
	cat /etc/pbs.conf > $pbs_newhome/mom$n/pbs.conf

	echo editing pbs.conf file and mom_priv/config
	mom_home=$pbs_newhome/mom$n
	rm -f $mom_home/mom_priv/mom.lock
	rm -f $mom_home/mom_priv/jobs/*
	rm -f $mom_home/mom_priv/hooks/*
	rm -f $mom_home/mom_logs/*
	conf_file=$mom_home/pbs.conf
	mom_conf=$mom_home/mom_priv/config

	if [ ! -f "$conf_file" ]; then
		echo "File $conf_file missing"
		return 1
	fi

	if [ ! -f "$mom_conf" ]; then
		echo "File $mom_conf missing"
		return 1
	fi

	echo "PBS_MOM_SERVICE_PORT=$port" >> $conf_file
	echo "PBS_MANAGER_SERVICE_PORT=`expr $port + 1`" >> $conf_file
	echo "PBS_HOME=$mom_home" >> $conf_file
	sed -i "s/PBS_SERVER=.*/PBS_SERVER=$server/g" $conf_file

	chown -R root ${mom_home}

	export PBS_ENVIRONMENT=$mom_home/pbs_environment

	echo starting mom $n
	PBS_CONF_FILE=$pbs_newhome/mom$n/pbs.conf $PBS_EXEC/sbin/pbs_mom 

	echo "Done"
	return 0
}

stop_mom()
{
	common
	mom_home=$pbs_newhome/mom$n
	pbs_mom_pid=`getpid ${mom_home}/mom_priv/mom.lock`
	kill -TERM ${pbs_mom_pid}
	rm -rf ${mom_home}
	echo "Done"
	return 0
}

echo "Starting with parameters: $*"

if [ $# -lt 1 ]; then
	usage
	exit 1
fi
oper=$1


if [ "$oper" = "start" ]; then
	if [ $# -lt 3 ]; then
		usage
		exit 1
	fi
	port=$2
	server=$3
	start_mom $port $server
	exit $?

elif [ "$oper" = "stop" ]; then
	stop_mom
	exit $?

else
	usage
	exit 1
fi
