#!/usr/bin/sh

if [ $# -lt 4 ]
then
	echo "Usage is: $0 <start> <end> <host> <port no.>"
	exit 
fi

. /etc/pbs.conf

l=$2
n=$1
host=$3
port=$4
ulimit -n 10000
ulimit -c unlimited
n=$1
while [ $n -le $l ]
do
	echo Querying mom $n
	mgr_port=`expr $port + 1`
	echo $PBS_EXEC/unsupported/pbs_rmget -m $host -p $mgr_port ncpu
	$PBS_EXEC/unsupported/pbs_rmget -m $host -p $mgr_port ncpu
	n=`expr $n + 1`
	port=`expr $port + 5`
done

echo "Done"
