#!/usr/bin/sh

if [ $# -lt 3 ]
then
	echo "Usage is: $0 <start> <end> <port no.> [router-names]"
	exit 
fi

l=$2
n=$1
port=$3
routers=""

echo "Moms required to be created are from $n to $l with port starting from $port"
if [ $# -eq 4 ]; then
	routers=$4
	echo "Router names for this bunch of moms set to $routers"
fi

. /etc/pbs.conf

ulimit -n 10000
ulimit -c unlimited

pbs_home=$PBS_HOME
pbs_newhome=`dirname $pbs_home`
if [ -z "$pbs_newhome" ]; then 
	echo "Could not detect new home"
	exit 1
fi

if [ ! -d "$pbs_newhome" ]; then 
	echo "$pbs_newhome is not a directory"
	exit 1
fi

if [ "$pbs_newhome" = "/" ]; then
	echo "pbs_newhome resolves to /. Cannot work"
	exit 1
fi

echo Current PBS_HOME=$pbs_home
echo Homes for new moms=$pbs_newhome

n=$1

echo creating mom directories
while [ $n -le $l ]
do
	mkdir $pbs_newhome/mom$n
	cp -r -p $pbs_home/aux $pbs_newhome/mom$n
	cp -r -p $pbs_home/checkpoint $pbs_newhome/mom$n
	cp -r -p $pbs_home/mom_logs $pbs_newhome/mom$n
	cp -r -p $pbs_home/pbs_environment $pbs_newhome/mom$n
	cp -r -p $pbs_home/mom_priv $pbs_newhome/mom$n
	cp -r -p $pbs_home/spool $pbs_newhome/mom$n
	cat /etc/pbs.conf > $pbs_newhome/mom$n/pbs.conf
	n=`expr $n + 1`
done
n=$1

echo editing pbs.conf file and mom_priv/config
while [ $n -le $l ]
do
	mom_home=$pbs_newhome/mom$n
	conf_file=$mom_home/pbs.conf
	mom_conf=$mom_home/mom_priv/config

	if [ ! -f "$conf_file" ]; then
		echo "File $conf_file missing"
		exit 1
	fi

	if [ ! -f "$mom_conf" ]; then
		echo "File $mom_conf missing"
		exit 1
	fi

	echo "PBS_MOM_SERVICE_PORT=$port" >> $conf_file
	echo "PBS_MANAGER_SERVICE_PORT=`expr $port + 1`" >> $conf_file
	echo "PBS_HOME=$mom_home" >> $conf_file
	if [ ! -z "${routers}" ]; then
		echo "PBS_LEAF_ROUTERS=${routers}" >> $conf_file
	fi

	chown -R root ${mom_home}

	port=`expr $port + 5`
	n=`expr $n + 1`
done
n=$1

port=$3
while [ $n -le $l ]
do
	echo starting mom $n
	mgr_port=`expr $port + 1`
	#PBS_CONF_FILE=$pbs_newhome/mom$n/pbs.conf valgrind --leak-check=full --log-file=mom_$n.log $PBS_EXEC/sbin/pbs_mom -p > out$n 2>&1  &
	PBS_CONF_FILE=$pbs_newhome/mom$n/pbs.conf $PBS_EXEC/sbin/pbs_mom  -p > out$n 2>&1  &
	n=`expr $n + 1`
	port=`expr $port + 5`
done

echo "Done"
