#!/usr/bin/sh

. /etc/pbs.conf
pbs_home=$PBS_HOME

pbs_newhome=`dirname $pbs_home`
if [ -z "$pbs_newhome" ]; then 
	echo "Could not detect new home"
	exit 1
fi

if [ ! -d "$pbs_newhome" ]; then 
	echo "$pbs_newhome is not a directory"
	exit 1
fi

if [ "$pbs_newhome" = "/" ]; then
	echo "pbs_newhome resolves to /. Cannot work"
	exit 1
fi

pids=`ps -ef | grep pbs_mom | grep -v pbs_comm | grep -v grep | awk '{print $2}'`
kill -9 $pids > /dev/null 2>&1

pids=`echo $pids | tr -s "\n" " "`
echo "Killing pids=$pids"

for momdir in `ls -d ${pbs_newhome}/mom*`
do
	rm -rf ${momdir}
done

rm -f ${PBS_HOME}/mom_logs/*
rm -f out*

